<?php
$this->headLink()->appendStylesheet($this->assetUrl('css/form.css', 'CollectingTogether'));
$this->headScript()->appendFile($this->assetUrl('js/form.js', 'CollectingTogether'));
?>

<?php echo $this->pageTitle('Find a collecting project', 2); ?>

<form id="collecting-together-form" autocomplete="off" data-projects-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'projects'], true)); ?>">
    <?php echo $this->formRow($this->cfSelect); ?>
    <?php echo $this->formRow($this->gfSelect); ?>
    <?php echo $this->formRow($this->mfSelect); ?>
    <?php echo $this->formRow($this->amSelect); ?>
</form>

<div id="collecting-together-projects"></div>
