<?php echo $this->pageTitle('Find a collecting project'); ?>

<form id="collecting-together-form" data-url="<?php echo $this->escapeHtml($this->url(null, ['action' => 'projects'], true)); ?>">
    <?php echo $this->formRow($this->categorySelect); ?>
    <?php echo $this->formRow($this->geographySelect); ?>
    <?php echo $this->formRow($this->materialSelect); ?>
    <?php echo $this->formRow($this->methodSelect); ?>
</form>

<div id="collecting-together-projects"></div>

<script>
const form = document.getElementById('collecting-together-form');
const categorySelect = document.getElementById('category-select');
const geographySelect = document.getElementById('geography-select');
const materialSelect = document.getElementById('material-select');
const methodSelect = document.getElementById('method-select');

form.addEventListener('submit', e => e.preventDefault());
form.addEventListener('change', e => {
    filterProjects();
});

async function filterProjects() {
    query = {
        category: categorySelect.value,
        geography: geographySelect.value,
        material: materialSelect.value,
        method: methodSelect.value,
    };
    let response = await fetch(form.dataset.url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(query)
    });
    let text = await response.text();
};
</script>
